### ISSUE TITLE
Werner hacker 

### ISSUE THREAD

**Issue by wernertimo8** [rajkumardusad/jitcompiler#5]
npm start has a proplm

**Comment by rajkumardusad** [comment]
> npm start has a proplm

What's the problem?

**Comment by hypesol** [comment]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/14737991/212290397-9fd49627-30c5-4b78-9047-8ca4b6479ebd.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/14737991/212290449-b343888a-efa8-4086-8d95-c5e9d9e70418.png">


Please check the above screenshots and plz let us know thanks

**Comment by rajkumardusad** [comment]
> <img alt="image" width="710" src="https://user-images.githubusercontent.com/14737991/212290397-9fd49627-30c5-4b78-9047-8ca4b6479ebd.png">
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/14737991/212290449-b343888a-efa8-4086-8d95-c5e9d9e70418.png">
> 
> Please check the above screenshots and plz let us know thanks

Which system you are using?
There is an issue you system has not apt package manager

**Comment by hypesol** [comment]
I am using MAC

**Comment by hypesol** [comment]
I am using MAC. now this script is started on mac but when I tried to compile any code I got this message

<img width="958" alt="image" src="https://user-images.githubusercontent.com/14737991/218379520-02f4aa8a-7944-4524-b13e-e9639b3d7034.png">

**Comment by rajkumardusad** [comment]
> I am using MAC. now this script is started on mac but when I tried to compile any code I got this message
> 
> <img alt="image" width="958" src="https://user-images.githubusercontent.com/14737991/218379520-02f4aa8a-7944-4524-b13e-e9639b3d7034.png">

Hey @hypesol jitcompiler requires docker to compiler languages, please follow all Installation step or do the all setup manually.
I hope it will works for you.
