### ISSUE TITLE
Ain't executing

### ISSUE THREAD

**Issue by Shivamkushwaha9** [rajkumardusad/jitcompiler#8]
I tried running the scripts but It won't execute, the output section remained blank for even a simple hello world ...Any solutions though?
![image](https://github.com/rajkumardusad/jitcompiler/assets/142090135/b506a2a7-c26d-46c3-9231-dc2e993ee227)

**Comment by rajkumardusad** [comment]
Is there are any error in console? Please setup the docker container and follow the instructions it will work.

**Comment by rajkumardusad** [comment]
Let me know if there is any error, it's working perfectly on linux systems.

**Comment by Shivamkushwaha9** [comment]
> Let me know if there is any error, it's working perfectly on linux systems.



> Is there are any error in console? Please setup the docker container and follow the instructions it will work.
